version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: daily
    time: "06:00"
    timezone: Europe/Stockholm
  open-pull-requests-limit: 10
  reviewers:
  - gonace
  ignore:
  - dependency-name: mongoid
    versions:
    - 7.0.12
    - 7.1.7
    - 7.2.1
  - dependency-name: activesupport
    versions:
    - 6.1.2
