spec:
  options:
    raise_not_found_error: false
  clients:
    default:
      database: timeline_testing
      hosts:
        - localhost:27017
      options:
        max_pool_size: 100
        min_pool_size: 5